# Import Dependencies

In [1]:
import atd2022
import torch
import pandas as pd
import numpy as np
from atd_informer import atd_informer
from utils.tools import dotdict

In [2]:
import importlib
importlib.reload(atd_informer)

<module 'atd_informer.atd_informer' from '/Users/will/LISP-ATD-2022/Informer/atd_informer/atd_informer.py'>

# Model Parameter Setting

In [10]:
args = dotdict()


args.enc_in = 5200 # encoder input size
args.dec_in = 5200 # decoder input size
args.c_out = 5200 # output size
args.factor = 5 # probsparse attn factor
args.d_model = 512 # dimension of model
args.n_heads = 8 # num of heads
args.e_layers = 2 # num of encoder layers
args.d_layers = 1 # num of decoder layers
args.d_ff = 2048 # dimension of fcn in model
args.dropout = 0.05 # dropout
args.attn = 'prob' # attention used in encoder, options:[prob, full]
args.embed = 'timeF' # time features encoding, options:[timeF, fixed, learned]
args.activation = 'gelu' # activation
args.distil = True # whether to use distilling in encoder
args.output_attention = False # whether to output attention in ecoder
args.mix = True
args.padding = 0
args.freq = 'w'
args.inverse=False
args.timeenc=0
args.checkpoints = "/Users/will/Desktop/tmp"



args.seq_len=5
args.label_len=3
args.pred_len=1


args.batch_size = 1
args.learning_rate = 0.0001
args.loss = 'mse'
args.lradj = 'type1'
args.use_amp = False

args.itr=1
args.train_epochs=1
args.patience=3

In [11]:
informer = atd_informer.ATD_Informer

# Model Training

In [12]:
for ii in range(args.itr):
        # setting record of experiments
    setting = '{}_{}_ft{}_sl{}_ll{}_pl{}_dm{}_nh{}_el{}_dl{}_df{}_at{}_fc{}_eb{}_dt{}_mx{}_{}_{}'.format(args.model, args.data, args.features, 
                args.seq_len, args.label_len, args.pred_len,
                args.d_model, args.n_heads, args.e_layers, args.d_layers, args.d_ff, args.attn, args.factor, args.embed, args.distil, args.mix, args.des, ii)

    # set experiments
    exp = informer(args)
    
    # train
    print('>>>>>>>start training : {}>>>>>>>>>>>>>>>>>>>>>>>>>>'.format(setting))
    exp.train(setting)
    
    # test
    print('>>>>>>>testing : {}<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<'.format(setting))
    exp.test(setting)

Use CPU
>>>>>>>start training : None_None_ftNone_sl5_ll3_pl1_dm512_nh8_el2_dl1_df2048_atprob_fc5_ebtimeF_dtTrue_mxTrue_None_0>>>>>>>>>>>>>>>>>>>>>>>>>>
timeenc, freq 1 w
timeenc, freq 1 w
timeenc, freq 1 w
pairs 0 5
y_pairs 2 6
dim: (5, 5200) (5, 2)
bxm-shape torch.Size([1, 5, 5200]) torch.Size([1, 5, 2]) torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
dec_inp_pre torch.Size([1, 1, 5200])
dec_inp_post torch.Size([1, 4, 5200])
triggered
ln1 torch.Size([1, 5, 5200]) torch.Size([1, 5, 2])
ln2 torch.Size([1, 5, 512]) torch.Size([1, 5, 512]) torch.Size([1, 5, 512])
triggered
ln1 torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
ln2 torch.Size([1, 4, 512]) torch.Size([1, 4, 512]) torch.Size([1, 4, 512])
pairs 1 6
y_pairs 3 7
dim: (5, 5200) (5, 2)
bxm-shape torch.Size([1, 5, 5200]) torch.Size([1, 5, 2]) torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
dec_inp_pre torch.Size([1, 1, 5200])
dec_inp_post torch.Size([1, 4, 5200])
triggered
ln1 torch.Size([1, 5, 5200]) torch.Size([1, 5, 2])
ln2 torch.Siz

pairs 16 21
y_pairs 18 22
dim: (5, 5200) (5, 2)
bxm-shape torch.Size([1, 5, 5200]) torch.Size([1, 5, 2]) torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
dec_inp_pre torch.Size([1, 1, 5200])
dec_inp_post torch.Size([1, 4, 5200])
triggered
ln1 torch.Size([1, 5, 5200]) torch.Size([1, 5, 2])
ln2 torch.Size([1, 5, 512]) torch.Size([1, 5, 512]) torch.Size([1, 5, 512])
triggered
ln1 torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
ln2 torch.Size([1, 4, 512]) torch.Size([1, 4, 512]) torch.Size([1, 4, 512])
pairs 17 22
y_pairs 19 23
dim: (5, 5200) (5, 2)
bxm-shape torch.Size([1, 5, 5200]) torch.Size([1, 5, 2]) torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
dec_inp_pre torch.Size([1, 1, 5200])
dec_inp_post torch.Size([1, 4, 5200])
triggered
ln1 torch.Size([1, 5, 5200]) torch.Size([1, 5, 2])
ln2 torch.Size([1, 5, 512]) torch.Size([1, 5, 512]) torch.Size([1, 5, 512])
triggered
ln1 torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
ln2 torch.Size([1, 4, 512]) torch.Size([1, 4, 512]) torch.Size([1, 4, 512]

pairs 34 39
y_pairs 36 40
dim: (5, 5200) (5, 2)
bxm-shape torch.Size([1, 5, 5200]) torch.Size([1, 5, 2]) torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
dec_inp_pre torch.Size([1, 1, 5200])
dec_inp_post torch.Size([1, 4, 5200])
triggered
ln1 torch.Size([1, 5, 5200]) torch.Size([1, 5, 2])
ln2 torch.Size([1, 5, 512]) torch.Size([1, 5, 512]) torch.Size([1, 5, 512])
triggered
ln1 torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
ln2 torch.Size([1, 4, 512]) torch.Size([1, 4, 512]) torch.Size([1, 4, 512])
pairs 35 40
y_pairs 37 41
dim: (5, 5200) (5, 2)
bxm-shape torch.Size([1, 5, 5200]) torch.Size([1, 5, 2]) torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
dec_inp_pre torch.Size([1, 1, 5200])
dec_inp_post torch.Size([1, 4, 5200])
triggered
ln1 torch.Size([1, 5, 5200]) torch.Size([1, 5, 2])
ln2 torch.Size([1, 5, 512]) torch.Size([1, 5, 512]) torch.Size([1, 5, 512])
triggered
ln1 torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
ln2 torch.Size([1, 4, 512]) torch.Size([1, 4, 512]) torch.Size([1, 4, 512]

pairs 51 56
y_pairs 53 57
dim: (5, 5200) (5, 2)
bxm-shape torch.Size([1, 5, 5200]) torch.Size([1, 5, 2]) torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
dec_inp_pre torch.Size([1, 1, 5200])
dec_inp_post torch.Size([1, 4, 5200])
triggered
ln1 torch.Size([1, 5, 5200]) torch.Size([1, 5, 2])
ln2 torch.Size([1, 5, 512]) torch.Size([1, 5, 512]) torch.Size([1, 5, 512])
triggered
ln1 torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
ln2 torch.Size([1, 4, 512]) torch.Size([1, 4, 512]) torch.Size([1, 4, 512])
pairs 52 57
y_pairs 54 58
dim: (5, 5200) (5, 2)
bxm-shape torch.Size([1, 5, 5200]) torch.Size([1, 5, 2]) torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
dec_inp_pre torch.Size([1, 1, 5200])
dec_inp_post torch.Size([1, 4, 5200])
triggered
ln1 torch.Size([1, 5, 5200]) torch.Size([1, 5, 2])
ln2 torch.Size([1, 5, 512]) torch.Size([1, 5, 512]) torch.Size([1, 5, 512])
triggered
ln1 torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
ln2 torch.Size([1, 4, 512]) torch.Size([1, 4, 512]) torch.Size([1, 4, 512]

pairs 69 74
y_pairs 71 75
dim: (5, 5200) (5, 2)
bxm-shape torch.Size([1, 5, 5200]) torch.Size([1, 5, 2]) torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
dec_inp_pre torch.Size([1, 1, 5200])
dec_inp_post torch.Size([1, 4, 5200])
triggered
ln1 torch.Size([1, 5, 5200]) torch.Size([1, 5, 2])
ln2 torch.Size([1, 5, 512]) torch.Size([1, 5, 512]) torch.Size([1, 5, 512])
triggered
ln1 torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
ln2 torch.Size([1, 4, 512]) torch.Size([1, 4, 512]) torch.Size([1, 4, 512])
pairs 70 75
y_pairs 72 76
dim: (5, 5200) (5, 2)
bxm-shape torch.Size([1, 5, 5200]) torch.Size([1, 5, 2]) torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
dec_inp_pre torch.Size([1, 1, 5200])
dec_inp_post torch.Size([1, 4, 5200])
triggered
ln1 torch.Size([1, 5, 5200]) torch.Size([1, 5, 2])
ln2 torch.Size([1, 5, 512]) torch.Size([1, 5, 512]) torch.Size([1, 5, 512])
triggered
ln1 torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
ln2 torch.Size([1, 4, 512]) torch.Size([1, 4, 512]) torch.Size([1, 4, 512]

pairs 87 92
y_pairs 89 93
dim: (5, 5200) (5, 2)
bxm-shape torch.Size([1, 5, 5200]) torch.Size([1, 5, 2]) torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
dec_inp_pre torch.Size([1, 1, 5200])
dec_inp_post torch.Size([1, 4, 5200])
triggered
ln1 torch.Size([1, 5, 5200]) torch.Size([1, 5, 2])
ln2 torch.Size([1, 5, 512]) torch.Size([1, 5, 512]) torch.Size([1, 5, 512])
triggered
ln1 torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
ln2 torch.Size([1, 4, 512]) torch.Size([1, 4, 512]) torch.Size([1, 4, 512])
pairs 88 93
y_pairs 90 94
dim: (5, 5200) (5, 2)
bxm-shape torch.Size([1, 5, 5200]) torch.Size([1, 5, 2]) torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
dec_inp_pre torch.Size([1, 1, 5200])
dec_inp_post torch.Size([1, 4, 5200])
triggered
ln1 torch.Size([1, 5, 5200]) torch.Size([1, 5, 2])
ln2 torch.Size([1, 5, 512]) torch.Size([1, 5, 512]) torch.Size([1, 5, 512])
triggered
ln1 torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
ln2 torch.Size([1, 4, 512]) torch.Size([1, 4, 512]) torch.Size([1, 4, 512]

pairs 105 110
y_pairs 107 111
dim: (5, 5200) (5, 2)
bxm-shape torch.Size([1, 5, 5200]) torch.Size([1, 5, 2]) torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
dec_inp_pre torch.Size([1, 1, 5200])
dec_inp_post torch.Size([1, 4, 5200])
triggered
ln1 torch.Size([1, 5, 5200]) torch.Size([1, 5, 2])
ln2 torch.Size([1, 5, 512]) torch.Size([1, 5, 512]) torch.Size([1, 5, 512])
triggered
ln1 torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
ln2 torch.Size([1, 4, 512]) torch.Size([1, 4, 512]) torch.Size([1, 4, 512])
pairs 106 111
y_pairs 108 112
dim: (5, 5200) (5, 2)
bxm-shape torch.Size([1, 5, 5200]) torch.Size([1, 5, 2]) torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
dec_inp_pre torch.Size([1, 1, 5200])
dec_inp_post torch.Size([1, 4, 5200])
triggered
ln1 torch.Size([1, 5, 5200]) torch.Size([1, 5, 2])
ln2 torch.Size([1, 5, 512]) torch.Size([1, 5, 512]) torch.Size([1, 5, 512])
triggered
ln1 torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
ln2 torch.Size([1, 4, 512]) torch.Size([1, 4, 512]) torch.Size([1,

pairs 123 128
y_pairs 125 129
dim: (5, 5200) (5, 2)
bxm-shape torch.Size([1, 5, 5200]) torch.Size([1, 5, 2]) torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
dec_inp_pre torch.Size([1, 1, 5200])
dec_inp_post torch.Size([1, 4, 5200])
triggered
ln1 torch.Size([1, 5, 5200]) torch.Size([1, 5, 2])
ln2 torch.Size([1, 5, 512]) torch.Size([1, 5, 512]) torch.Size([1, 5, 512])
triggered
ln1 torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
ln2 torch.Size([1, 4, 512]) torch.Size([1, 4, 512]) torch.Size([1, 4, 512])
pairs 124 129
y_pairs 126 130
dim: (5, 5200) (5, 2)
bxm-shape torch.Size([1, 5, 5200]) torch.Size([1, 5, 2]) torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
dec_inp_pre torch.Size([1, 1, 5200])
dec_inp_post torch.Size([1, 4, 5200])
triggered
ln1 torch.Size([1, 5, 5200]) torch.Size([1, 5, 2])
ln2 torch.Size([1, 5, 512]) torch.Size([1, 5, 512]) torch.Size([1, 5, 512])
triggered
ln1 torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
ln2 torch.Size([1, 4, 512]) torch.Size([1, 4, 512]) torch.Size([1,

pairs 141 146
y_pairs 143 147
dim: (5, 5200) (5, 2)
bxm-shape torch.Size([1, 5, 5200]) torch.Size([1, 5, 2]) torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
dec_inp_pre torch.Size([1, 1, 5200])
dec_inp_post torch.Size([1, 4, 5200])
triggered
ln1 torch.Size([1, 5, 5200]) torch.Size([1, 5, 2])
ln2 torch.Size([1, 5, 512]) torch.Size([1, 5, 512]) torch.Size([1, 5, 512])
triggered
ln1 torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
ln2 torch.Size([1, 4, 512]) torch.Size([1, 4, 512]) torch.Size([1, 4, 512])
pairs 142 147
y_pairs 144 148
dim: (5, 5200) (5, 2)
bxm-shape torch.Size([1, 5, 5200]) torch.Size([1, 5, 2]) torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
dec_inp_pre torch.Size([1, 1, 5200])
dec_inp_post torch.Size([1, 4, 5200])
triggered
ln1 torch.Size([1, 5, 5200]) torch.Size([1, 5, 2])
ln2 torch.Size([1, 5, 512]) torch.Size([1, 5, 512]) torch.Size([1, 5, 512])
triggered
ln1 torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
ln2 torch.Size([1, 4, 512]) torch.Size([1, 4, 512]) torch.Size([1,

triggered
ln1 torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
ln2 torch.Size([1, 4, 512]) torch.Size([1, 4, 512]) torch.Size([1, 4, 512])
pairs 14 19
y_pairs 16 20
dim: (5, 5200) (5, 2)
bxm-shape torch.Size([1, 5, 5200]) torch.Size([1, 5, 2]) torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
dec_inp_pre torch.Size([1, 1, 5200])
dec_inp_post torch.Size([1, 4, 5200])
triggered
ln1 torch.Size([1, 5, 5200]) torch.Size([1, 5, 2])
ln2 torch.Size([1, 5, 512]) torch.Size([1, 5, 512]) torch.Size([1, 5, 512])
triggered
ln1 torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
ln2 torch.Size([1, 4, 512]) torch.Size([1, 4, 512]) torch.Size([1, 4, 512])
pairs 15 20
y_pairs 17 21
dim: (5, 5200) (5, 2)
bxm-shape torch.Size([1, 5, 5200]) torch.Size([1, 5, 2]) torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
dec_inp_pre torch.Size([1, 1, 5200])
dec_inp_post torch.Size([1, 4, 5200])
triggered
ln1 torch.Size([1, 5, 5200]) torch.Size([1, 5, 2])
ln2 torch.Size([1, 5, 512]) torch.Size([1, 5, 512]) torch.Size([1, 5, 512]

ln2 torch.Size([1, 5, 512]) torch.Size([1, 5, 512]) torch.Size([1, 5, 512])
triggered
ln1 torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
ln2 torch.Size([1, 4, 512]) torch.Size([1, 4, 512]) torch.Size([1, 4, 512])
pairs 31 36
y_pairs 33 37
dim: (5, 5200) (5, 2)
bxm-shape torch.Size([1, 5, 5200]) torch.Size([1, 5, 2]) torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
dec_inp_pre torch.Size([1, 1, 5200])
dec_inp_post torch.Size([1, 4, 5200])
triggered
ln1 torch.Size([1, 5, 5200]) torch.Size([1, 5, 2])
ln2 torch.Size([1, 5, 512]) torch.Size([1, 5, 512]) torch.Size([1, 5, 512])
triggered
ln1 torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
ln2 torch.Size([1, 4, 512]) torch.Size([1, 4, 512]) torch.Size([1, 4, 512])
pairs 32 37
y_pairs 34 38
dim: (5, 5200) (5, 2)
bxm-shape torch.Size([1, 5, 5200]) torch.Size([1, 5, 2]) torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
dec_inp_pre torch.Size([1, 1, 5200])
dec_inp_post torch.Size([1, 4, 5200])
triggered
ln1 torch.Size([1, 5, 5200]) torch.Size([1, 5, 2]

pairs 11 16
y_pairs 13 17
dim: (5, 5200) (5, 2)
bxm-shape torch.Size([1, 5, 5200]) torch.Size([1, 5, 2]) torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
dec_inp_pre torch.Size([1, 1, 5200])
dec_inp_post torch.Size([1, 4, 5200])
triggered
ln1 torch.Size([1, 5, 5200]) torch.Size([1, 5, 2])
ln2 torch.Size([1, 5, 512]) torch.Size([1, 5, 512]) torch.Size([1, 5, 512])
triggered
ln1 torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
ln2 torch.Size([1, 4, 512]) torch.Size([1, 4, 512]) torch.Size([1, 4, 512])
pairs 12 17
y_pairs 14 18
dim: (5, 5200) (5, 2)
bxm-shape torch.Size([1, 5, 5200]) torch.Size([1, 5, 2]) torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
dec_inp_pre torch.Size([1, 1, 5200])
dec_inp_post torch.Size([1, 4, 5200])
triggered
ln1 torch.Size([1, 5, 5200]) torch.Size([1, 5, 2])
ln2 torch.Size([1, 5, 512]) torch.Size([1, 5, 512]) torch.Size([1, 5, 512])
triggered
ln1 torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
ln2 torch.Size([1, 4, 512]) torch.Size([1, 4, 512]) torch.Size([1, 4, 512]

triggered
ln1 torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
ln2 torch.Size([1, 4, 512]) torch.Size([1, 4, 512]) torch.Size([1, 4, 512])
pairs 8 13
y_pairs 10 14
dim: (5, 5200) (5, 2)
bxm-shape torch.Size([1, 5, 5200]) torch.Size([1, 5, 2]) torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
dec_inp_pre torch.Size([1, 1, 5200])
dec_inp_post torch.Size([1, 4, 5200])
triggered
ln1 torch.Size([1, 5, 5200]) torch.Size([1, 5, 2])
ln2 torch.Size([1, 5, 512]) torch.Size([1, 5, 512]) torch.Size([1, 5, 512])
triggered
ln1 torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
ln2 torch.Size([1, 4, 512]) torch.Size([1, 4, 512]) torch.Size([1, 4, 512])
pairs 9 14
y_pairs 11 15
dim: (5, 5200) (5, 2)
bxm-shape torch.Size([1, 5, 5200]) torch.Size([1, 5, 2]) torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
dec_inp_pre torch.Size([1, 1, 5200])
dec_inp_post torch.Size([1, 4, 5200])
triggered
ln1 torch.Size([1, 5, 5200]) torch.Size([1, 5, 2])
ln2 torch.Size([1, 5, 512]) torch.Size([1, 5, 512]) torch.Size([1, 5, 512])


# Generate Prediction

#setting = '{}_{}_ft{}_sl{}_ll{}_pl{}_dm{}_nh{}_el{}_dl{}_df{}_at{}_fc{}_eb{}_dt{}_mx{}_{}_{}'.format(args.model, args.data, args.features, 
                                                                                                     args.seq_len, args.label_len, args.pred_len,
                                                                                                     args.d_model, args.n_heads, args.e_layers, args.d_layers,
                                                                                                     args.d_ff, args.attn, args.factor, args.embed, args.distil, 
                                                                                                     args.mix, args.des)

In [13]:
setting= "string"

In [14]:
exp.predict(setting)

timeenc, freq 1 W
check data_x shape (30, 5200)
check data_y shape (30, 5200)
data_x [[  1   1   4 ...  52 414   0]
 [ 19   5   3 ... 126 275   6]
 [ 14   1  10 ... 118 262   0]
 ...
 [  5   2   0 ...  45 191   9]
 [  3   2   7 ... 139 175   3]
 [  7   6   7 ...  73 150   0]]
data_y [[  1   1   4 ...  52 414   0]
 [ 19   5   3 ... 126 275   6]
 [ 14   1  10 ... 118 262   0]
 ...
 [  5   2   0 ...  45 191   9]
 [  3   2   7 ... 139 175   3]
 [  7   6   7 ...  73 150   0]]
check_indices 0 5 2 6
check_r_sizes 2 6 3 1
x,y [[   1    1    4 ...   52  414    0]
 [  19    5    3 ...  126  275    6]
 [  14    1   10 ...  118  262    0]
 [  14    3    1 ...  125  197    3]
 [  33    9    8 ... 1093  326    1]] [[  14    1   10 ...  118  262    0]
 [  14    3    1 ...  125  197    3]
 [  33    9    8 ... 1093  326    1]] [[ 0.03333333  0.03846154]
 [ 0.26666667  0.05769231]
 [ 0.5         0.07692308]
 [-0.3         0.09615385]
 [-0.06666667  0.11538462]] [[ 0.5         0.07692308]
 [-0.3         

triggered
ln1 torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
ln2 torch.Size([1, 4, 512]) torch.Size([1, 4, 512]) torch.Size([1, 4, 512])
check_indices 8 13 10 14
check_r_sizes 10 14 3 1
x,y [[ 13   5   1 ... 119 177   5]
 [ 14   5   5 ... 120 113   3]
 [  6   2   6 ...  61 146   4]
 [ 24   6   1 ... 117 201   0]
 [ 12   7   1 ...  57 202   1]] [[  6   2   6 ...  61 146   4]
 [ 24   6   1 ... 117 201   0]
 [ 12   7   1 ...  57 202   1]] [[-0.16666667  0.19230769]
 [ 0.06666667  0.21153846]
 [ 0.3         0.23076923]
 [-0.46666667  0.25      ]
 [-0.23333333  0.26923077]] [[ 0.3         0.23076923]
 [-0.46666667  0.25      ]
 [-0.23333333  0.26923077]
 [ 0.          0.28846154]]
check sizes (5, 5200) (3, 5200) (5, 2) (4, 2)
bxm-shape torch.Size([1, 5, 5200]) torch.Size([1, 5, 2]) torch.Size([1, 3, 5200]) torch.Size([1, 4, 2])
dec_inp_pre torch.Size([1, 1, 5200])
dec_inp_post torch.Size([1, 4, 5200])
triggered
ln1 torch.Size([1, 5, 5200]) torch.Size([1, 5, 2])
ln2 torch.Size([1, 5, 512]) t

check_indices 22 27 24 28
check_r_sizes 24 28 3 1
x,y [[  3   3   4 ...  86 192   0]
 [  0   0   0 ...  25 130   0]
 [  7   5  26 ...  45 210   2]
 [ 13   9  20 ...  79 192   2]
 [ 14   5   8 ...  87 192   2]] [[  7   5  26 ...  45 210   2]
 [ 13   9  20 ...  79 192   2]
 [ 14   5   8 ...  87 192   2]] [[ 0.06666667  0.46153846]
 [ 0.3         0.48076923]
 [-0.5        -0.5       ]
 [-0.26666667 -0.48076923]
 [-0.03333333 -0.46153846]] [[-0.5        -0.5       ]
 [-0.26666667 -0.48076923]
 [-0.03333333 -0.46153846]
 [ 0.2        -0.44230769]]
check sizes (5, 5200) (3, 5200) (5, 2) (4, 2)
bxm-shape torch.Size([1, 5, 5200]) torch.Size([1, 5, 2]) torch.Size([1, 3, 5200]) torch.Size([1, 4, 2])
dec_inp_pre torch.Size([1, 1, 5200])
dec_inp_post torch.Size([1, 4, 5200])
triggered
ln1 torch.Size([1, 5, 5200]) torch.Size([1, 5, 2])
ln2 torch.Size([1, 5, 512]) torch.Size([1, 5, 512]) torch.Size([1, 5, 512])
triggered
ln1 torch.Size([1, 4, 5200]) torch.Size([1, 4, 2])
ln2 torch.Size([1, 4, 512]) 

In [15]:
prediction = np.load('./results/'+setting+'/real_prediction.npy')

prediction.shape

(26, 1, 5200)

In [16]:
prediction

array([[[4.514231 , 3.8869922, 4.6854606, ..., 6.838047 , 7.110626 ,
         1.2478503]],

       [[4.5231624, 3.8945708, 4.6614823, ..., 6.844203 , 7.0963926,
         1.2474967]],

       [[4.4990997, 3.8935337, 4.660523 , ..., 6.8790097, 7.0999537,
         1.2301582]],

       ...,

       [[4.519049 , 3.8846028, 4.743504 , ..., 6.933771 , 7.126029 ,
         1.2668412]],

       [[4.529879 , 3.9023826, 4.7047367, ..., 6.914223 , 7.1053276,
         1.26222  ]],

       [[4.47649  , 3.9167457, 4.6164346, ..., 6.8360767, 7.0631123,
         1.2432259]]], dtype=float32)